### ISSUE TITLE
Provision Workflow step fails. List provisioning missing?

### ISSUE THREAD

**Issue by RainerAtSpirit** [OfficeDev/Property-Inspection-Code-Sample#2]
After the initial step that creates the site collection, the next step `Provision Workflow` fails.
It looks like https://github.com/OfficeDev/Property-Inspection-Code-Sample/blob/master/PropertyManagerMyApp/PropertyManagerMyApp/Controllers/O365SiteProvisioningController.cs#L127 tries to access a list `Incidents` that is not created. 

Is there a step that I'm missing step that provisions the required lists?

**Comment by RainerAtSpirit** [comment]
Never mind. After deleting the site collection and removing from the recycle bin, the second time the provisioning worked as documented.

**Comment by TBag** [comment]
The AddSiteComponents method creates the various content types, lists, and, libraries which are part of the sample.  Take a look in the All Site Contents page to see if each of these items has been created successfully.  If they are all present, try to provision the workflow again.  If they are not there then delete the site collection the code provisioned, check all your web.config settings, and recreate it.
