### ISSUE TITLE
Project is missing the App_Data folder

### ISSUE THREAD

**Issue by melzoghbi** [OfficeDev/Property-Inspection-Code-Sample#3]
Hi Todd,

The project is missing the App_Data folder, if you can add this to the repo would be great. Thanks.

**Comment by TBag** [comment]
Please let me know which module and projects you are referring to.

**Comment by TBag** [comment]
Oh, you must be referring to the web app.  I am about to push a new version of the entire sample to GitHub that includes updates to work with the GA version of the Graph API as well as additional functionality related to many O365 services.  Keep an eye on the repo, this should occur int he next few days.

**Comment by melzoghbi** [comment]
Thanks for the quick reply, I am taking about the asp.net MVC project "PropertyManagerMyApp" Folder.

**Comment by melzoghbi** [comment]
OK. Thanks for the update.

**Comment by TBag** [comment]
Just pushed the latest version.  Please try it out and let us know what you think.  The App_Data folder is no longer part of the project.
