### ISSUE TITLE
Site collection provisioning fails with "Access denied"

### ISSUE THREAD

**Issue by jasonjoh** [OfficeDev/Property-Inspection-Code-Sample#5]
When setting up the web app and going through the steps to provision the site collection, I was consistently getting the error in the UI that says: 

`An error occurred.  This is usually due to one of two reasons.  1. You did not log in with an account that is a Global Administrator for your tenancy.  If you have logged in with a Global Administrator account, log out and close all browser windows then try this step again.  2. The site collection exists in the Recycle Bin.  If the Site Collection still exists in the Recycle Bin use the SharePoint Online Management Shell to delete it completely. The How to re-provision the entire information architecture and demo data section in the README describes how to use the following command to delete the site collection from the Recycle Bin. Remove-SPODeletedSite -Identity <Site Collection URL>`

As it turns out, it was the first call to create a site column that was returning an error: "Access Denied". I'm guessing that at the time of writing the preview SharePoint scopes would allow you to create site columns, but I guess that's no longer the case.

To get this working, since it's a one-time provision, I cribbed the code from http://www.wictorwilen.se/Post/How-to-do-active-authentication-to-Office-365-and-SharePoint-Online.aspx (patched it up to modern .NET), and hard-coded my admin username/pw. That got me past the error.

**Comment by TBag** [comment]
@jasonjoh Thanks for the bug report and how you resolved it.  We are looking into this and will get things fixed ASAP.

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
